version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  web: 
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
      
# docker-compose up
